Add step to install system dependencies in README
coredump-ch/interna pull request #62
Opened 2021-05-12 15:31 UTC by rnestler

Without postgresql installed, the installation of the Python packages
will fail.

2021-05-12 16:07 UTC, dbrgn reviewed
Hm, die Voraussetzungen (inkl. PostgreSQL) sind ein paar Zeilen weiter oben schon dokumentiert. Und Pacman ist Arch-spezifisch. Warum ist Python und Pip hier nicht auch aufgelistet? Bist du sicher, dass der Eintrag Mehrwert bringt?

(Falls ja, vor dem Merge noch einen Bindestrich in "System-Abhängigkeiten" rein 🙂)

2021-05-13 11:33 UTC, rnestler commented
Naja, dass ich Python brauche hat mich nicht so überrascht, dass ich aber postgrsql installiert haben muss um das Python Paket zu installieren schon.
Was auch hilfreich wäre: Eine Anleitung um die inotiale Datenbank zu erstellen.

2021-05-13 12:09 UTC, dbrgn commented
> Was auch hilfreich wäre: Eine Anleitung um die inotiale Datenbank zu erstellen.

Lies' doch mal 2 Zeilen über deiner Änderung 😅 Da steht der "createdb"-Command.

2021-05-18 14:23 UTC, rnestler commented
> Lies' doch mal 2 Zeilen über deiner Änderung sweat_smile Da steht der "createdb"-Command.

Ja, der funktioniert aber nicht einfach so:
```
createdb: error: could not connect to database template1: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/run/postgresql/.s.PGSQL.5432"?
```
```
% sudo systemctl status postgresql.service
× postgresql.service - PostgreSQL database server
     Loaded: loaded (/usr/lib/systemd/system/postgresql.service; disabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Tue 2021-05-18 16:22:50 CEST; 1s ago
    Process: 57477 ExecStartPre=/usr/bin/postgresql-check-db-dir ${PGROOT}/data (code=exited, status=1/FAILURE)
        CPU: 19ms

Mai 18 16:22:50 sekalo systemd[1]: Starting PostgreSQL database server...
Mai 18 16:22:50 sekalo postgres[57477]: "/var/lib/postgres/data" is missing or empty. Use a command like
Mai 18 16:22:50 sekalo postgres[57477]:   su - postgres -c "initdb --locale en_US.UTF-8 -D '/var/lib/postgres/data'"
Mai 18 16:22:50 sekalo postgres[57477]: with relevant options, to initialize the database cluster.
Mai 18 16:22:50 sekalo systemd[1]: postgresql.service: Control process exited, code=exited, status=1/FAILURE
Mai 18 16:22:50 sekalo systemd[1]: postgresql.service: Failed with result 'exit-code'.
Mai 18 16:22:50 sekalo systemd[1]: Failed to start PostgreSQL database server.
```

2021-05-18 14:34 UTC, rnestler commented
Mit
```
sudo su - postgres -c "initdb --locale en_US.UTF-8 -D '/var/lib/postgres/data'"
sudo su - postgres -c "createuser $USER"
createdb interna
```
Hat's dann funktioniert.

2021-05-23 21:54 UTC, dbrgn requested changes
> Ja, der funktioniert aber nicht einfach so:

Das liegt aber an Arch Linux, wo das Setup manuell ist und der DB Cluster nicht automatisch initialisiert wird: https://wiki.archlinux.org/title/PostgreSQL Du musst auch zB bei Major Upgrades manuell den DB-Cluster upgraden. (Ich habe deswegen postgresql-* in pacman für Updates blacklisted. Steht im Arch-Wiki.) Das sind aber alles Dinge die je nach Distro anders sind, auf Ubuntu oder Fedora wird deine Anleitung so schonmal nicht funktionieren. Und auf macOS auch nicht.

Gerade weil diese Dinge sehr spezifisch für Arch-User sind, würde ich das gerne nicht ins README packen, sondern einfach hinschreiben "du brauchst eine funktionierende PostgreSQL-Installation". Man kann ja ggf. für Arch User das Wiki verlinken. Je nach Version könnte sich diese Anleitung nämlich auch verändern / unterschiedlich sein.

Wenn's dir wichtig ist, dass das Setup möglichst einfach einzurichten ist, könnte man Postgres auch mit einer fixen Version in einem Docker-Container starten. Dann braucht man aber Docker, was auch zuerst eingerichtet werden muss 😉

Hier mal ein Vorschlag für eine Setup-Anleitung, die man nicht für jede Distro separat updaten muss.

2021-05-23 21:54 UTC, dbrgn commented on README.md
> +
```suggestion
Für Arch Linux Benutzer ist das Setup von PostgreSQL hier beschrieben: <https://wiki.archlinux.org/title/PostgreSQL>

```

2021-05-23 21:54 UTC, dbrgn commented on README.md
>      createdb interna
```suggestion
    createdb interna
    
(Falls dieser Befehl aufgrund eines Berechtigungs-Problems nicht funktioniert, muss ggf. zuerst ein lokaler Postgres-Benutzer angelegt werden: `sudo -u postgres createuser --superuser $USER`)
```

2021-05-25 11:19 UTC, rnestler commented on README.md
>      createdb interna
Warum grad `--superuser` anstelle von `--createdb`?

2021-05-25 11:47 UTC, dbrgn commented on README.md
>      createdb interna
Ist die einfachste Variante für lokale Entwicklung, wo Rechte-Management keine Rolle spielt... `--createdb` würde wohl auch reichen.

2021-10-04 12:11 UTC, dbrgn commented
@rnestler ping 🙂

2021-11-15 22:28 UTC, closed without merging